server:
  port: 8083

spring:
  application:
    name: johnny-gateway-service  # 你的服务名，必须和Nacos dataId前缀一致
  # 核心：新版拉取Nacos配置的写法
  config:
    import:
      nacos:${spring.application.name}.yaml # 自动读取 服务名.yaml
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # 👈改成 false，关闭自动路由
          lower-case-service-id: true
    nacos:
      # Nacos配置中心地址
      config:
        server-addr: 121.43.195.26:8848
        namespace: fc980474-f863-404b-b5d2-b493c4a53c16
        group: DEFAULT_GROUP
        file-extension: yml # 后缀
      discovery:
        server-addr: 121.43.195.26:8848
        namespace: fc980474-f863-404b-b5d2-b493c4a53c16
        group: DEFAULT_GROUP
        file-extension: yml # 后缀